### ISSUE TITLE
多线路CDN地址解析

### ISSUE THREAD

**Issue by Lazy6Studio** [packenx/DouyuInfo#1]
大大有思路弄CDN直播地址获取的分析么？尝试了在几个地方加&cdn=XXX之类的参数但是暂时还没有成功

**Comment by packenx** [comment]
是指切换线路吗 [GitHub Search](https://github.com/search?utf8=%E2%9C%93&q=douyutv.com%2Fswf_api%2Froom%2F&type=Code&ref=searchresults)

**Comment by Lazy6Studio** [comment]
对。哎我先试下你上面这Search的结果
